# Generated by Django 3.2.13 on 2022-06-23 09:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_created_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 23, 9, 34, 48, 348671, tzinfo=utc), verbose_name='创建时间'),
        ),
    ]
