# Generated by Django 3.2.13 on 2022-06-24 07:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_created_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 24, 7, 24, 11, 612190, tzinfo=utc), verbose_name='创建时间'),
        ),
    ]
